name: Validate

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified
