name: Validate

on:
  workflow_call:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure git is installed
        run: sudo apt-get update && sudo apt-get install -y git

      - uses: athombv/github-action-homey-app-validate@master
        with:
          level: verified
